POST http://localhost:3001/api/bicycles
Content-Type: application/json
Authorization: Bearer 090c1acdf9cf75af107b

{
  "color": "verde",
  "model": "todo terreno",
  "latitude": "-34.603722",
  "length": "-58.381592"
}

###

# withouth token
POST http://localhost:3000/api/bicycles
Content-Type: application/json


###

# withouth content
POST http://localhost:3000/api/bicycles
Content-Type: application/json

{
}