version: '3'
services:

  frontend:
    image: bicy-nextjs-prod:0.0.1
    build:
      context: ./bicyrent-app
      dockerfile: ../provision/frontend/production/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL_SERVER=http://localhost:3001
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - main
    depends_on:
      - database

  backend:
    image: bicy-ruby-prod:0.0.1
    build:
      context: ./backend
      dockerfile: ../provision/backend/production/Dockerfile
    environment:
      - RAILS_ENV=production
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - main
    volumes:
      - ./backend:/app
    depends_on:
      - database

  database:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bicyrentApp
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - main
    env_file:
      - .env

volumes:
  database:


networks:
  main:
