apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicyrent-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicyrent-back
  template:
    metadata:
      labels:
        app: bicyrent-back
    spec:
      containers:
      - name: bicyrent-back
        # image: bicyrentacr.azurecr.io/bicy-ruby-prod:v1
        image: miltoncodeyt/bicy-ruby-prod:0.0.1
        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@postgres-database/bicyrentApp"
          - name: RAILS_ENV
            value: production
        ports:
        - containerPort: 3001