apiVersion: v1
kind: Service
metadata:
  name: postgres-database
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
